### ISSUE TITLE
[AddOn] Can't move map view

### ISSUE THREAD

**Issue by RamiLego4Game** [micdoodle8/Galacticraft#1380]
I'm programming an add-on that has a new solar system, when i need to go to a planet at it i have to switch to fullscreen then zoom out and click at the planet icon, + when i double click planet icon the screen zooms into random position!

Please re-enable map movement like GC2

**Comment by radfast** [comment]
Is this the same issue as #1269?

**Comment by RamiLego4Game** [comment]
The same of my second problem after "+", but the main problem that we should me able to move the map.

Well, i was thinking, what about when someone clicked a planet at other solarsystem, the map origin changes to the main star of the other solarsystem and then zoom to the planet, so the zooming is fixed.

**Comment by BlesseNtumble** [comment]
A similar problem.
 I tried to make a new star. And I have it even happened. But when you click on it 2 - Zoom out between the orbits of Jupiter and Saturn. Into the void. 
 + I think that still need to make a list of stars. To register a star on the list

**Comment by BlesseNtumble** [comment]
+ Return movement buttons WASD in Planet Map

**Comment by RamiLego4Game** [comment]
@BlesseNtumble By reading GC api you can easily create a list of stars without changing it.

**Comment by morlanius** [comment]
Using another addon that is already in a working stage, this problem still happens. If you click on the other star you have to zoom manually and not click anything, if you use the double click action to centre on an object not in the Sol system it will translate off to one side and zoom impossibly far in. 

It looks like the zoom action is not taking the star, so to me, it looks like you have a variable in there in the zooming functions that is referencing the centre point of the star that is being observed that is not being updated with the currently selected star so when you touch anything with those controls its zooming to Sol again. I suspect that some garbage value is being parsed when using the quick zoom method setting everything to 0 or -1 giving a zoom level so deep that the NSA would be envious eg: 1 grid gradation takes up 90% of the screen.

**Comment by radfast** [comment]
The great thing about this being an open-source mod is it's open to anyone who spots the reason for an issue, to make a pull request :D :p
