### ISSUE TITLE
Please add Galacticraft to CurseForge to support modpack developers

### ISSUE THREAD

**Issue by twothe** [micdoodle8/Galacticraft#2031]
Curse has added the ability to create mod-packs using the Curse Launcher. The tool is comfortable to use and allows mod-pack creators to reach a solid base of users, however for licensing reasons Curse only allows mods that are hosted on CurseForge or FTB. They allow for any kind of license including custom ones like Galacticraft has.

It would be a great support for mod-pack creators if you can [add the latest Galacticraft files to CurseForge](http://minecraft.curseforge.com/mc-mods/create). There is nothing else required but to upload the files there, so this basically involves no work from your side, but would be a huge benefit for us.

**Comment by radfast** [comment]
I will discuss with @micdoodle8.  I'm not too sure if this is likely to happen or not.

Does Curse force the modpacks always to use the latest version of the mod?

**Comment by M64mc** [comment]
@radfast "Does Curse force the modpacks always to use the latest version of the mod?"
Modpacks can choose the versions. Users can update, but they don't have to.

**Comment by P1-Kashwak** [comment]
just a little tip for people wanting to use it on Curse. You already can. If you do not know have a look at the 3rd Party List Located here. 

https://docs.google.com/spreadsheets/d/1SUxIEfbAf8tqAJP-HXnT0sPOY3atCF1OKy56cHxKNdk/edit#gid=0

There is a lot of mods that you are allowed to use.

**Comment by radfast** [comment]
@P1-Kashwak and others: 

That 3rd Party List refers to an outdated modpack permission for Galacticraft, and even the outdated permission which is linked to there was not always being complied with, as it required the modpack to provide, on its download page, a link to www.micdoodle8.com.

The correct current position for modpack permissions is explained here: http://wiki.micdoodle8.com/wiki/Modpack_Permission   As long as a modpack does everything which is said **there**, it will be fine with us.

We are reviewing the Curse situation and deciding what's best to do here, and we may have to notify Curse if that 3rd Party List needs to be changed.

**Comment by Chekote** [comment]
Any update on this? Galacticraft is now available for 1.11.2, and I'd like to use Curse to add it to my mocpack.

**Comment by radfast** [comment]
Currently you have permission to include a copy of Galacticraft in your modpacks on Curse (so you'd need to put the Galacticraft .jar files in the download with your configs and whatever else is yours)

https://wiki.micdoodle8.com/wiki/Modpack_Permission

The most important obligation is for you to keep updating Galacticraft.  Especially at the moment when 1.11.2 is so new, we will be updating Galacticraft a lot, and if you don't keep reasonably up to date then your players may be experiencing issues which are fixed.   We aim to make sure that our updates never break compatibility with past versions, so you shouldn't have to test Galacticraft in your pack each time.  (Unless your pack also has Galacticraft add-ons - the add-ons need to keep up with updates to Galacticraft itself, obviously!)

**Comment by marcus8448** [comment]
Can this be closed now?

**Comment by twothe** [comment]
Currently I can install various addons for Galacticraft via Twitch client (formerly known as Curse), however I still cannot install Galacticraft itself. This is confusing. I still would love to see Galacticraft to be installable via Twitch client.

**Comment by radfast** [comment]
@twothe see earlier responses.  Installing Galacticraft from our download site is just as fast as installing it from Curse, and any reasonable Google search should take you straight to the correct site.

@marcus8448 I will leave this open for now, for information for people who think it's an "issue".

**Comment by Clintomus** [comment]
It is actually an issue, you say its a "reasonable" Google search to get to where this mod can be downloaded. Well I say in response "any reasonable developer" would ensure access to the downloads with as close to 100% uptime as possible. The last 8 or so times I have tried to grab your mod, your site has been down. Can't distribute your projects if I can't download them now can you?

I've seen other mod developers do this as well, and I have no idea why they do. Twitch/Curse is a mod project site that provides the ability for you to set your updates as Alpha, Beta, or Release, and it is actually faster to go through Twitch than it is through your site for obvious UPTIME reasons. It is also more accessable for people to discuss the mod, report issues, find any mod dependancies, and find modpacks that utilize your mod as well as having a way to create a wiki for it. Excuse me if I sound upset, but it seems rather arrogant to rely on your AIMS and your own download site. And it would be right for ANYONE to be upset at you all for not aiding in the ease of access of your work.

And before you respond with the May 30th comment, yeah, you AIM to not break things, but unless you have some rediculous team of 200 people who pick each bit apart and compare it to each other individual bit, you're going to need people who will want to play your mod.

I guess it really is no wonder that someone else is developing an open ended space exploration mod, and being added to more current modpacks than this now dying project.

There is my two cents as far as this goes. And now, my OBLIGATION is to provide my players with a pack that is as easily accessable, as it is maintained and where they can more readily report any issues of conflicts with other mods in a streamlined manner where modpack makers can even get easy resolutions and downloads... Aka I'M USING ADVANCED ROCKETRY since they are actually wise about what they are doing and available on Curse.

**Comment by Thyriel** [comment]
> The most important obligation is for you to keep updating Galacticraft. Especially at the moment when 1.11.2 is so new, we will be updating Galacticraft a lot, and if you don't keep reasonably up to date then your players may be experiencing issues which are fixed.

Especially because of this you should really consider putting Galacticraft on curseforge. When you do a modpack you easily have a couple hundred mods and it's just insane checking them all by hand if they have an update available. The twitch client does that automatically, so when i'm working on a new modpack version the first and last thing i do is opening my custom project in the twitch client and letting it update the mods to their newest version.
A mod not on curseoforge can't be updated with that process, so you always have to check manually a website for updates. (And for some reason there's always the slightly risk that twitch bugs around and silently deletes mods from the project folder that are not on curseforge)

Imho you should really consider using curseforge like everyone else. (Btw you also get paid for downloads. Not enough that an uncommon mod with a couple thousand downloads would ever generate enough points so you really would get paid, but i'm sure a popular mod like galacticraft could easily hit the couple hundred k to million downloads needed to generate enough points for some nice payouts)

**Comment by radfast** [comment]
Thanks @Thyriel you make some good points

Ultimately it's micdoodle8's decision.  There are some good reasons why we use our current system, including ease of maintenance for us as devs, as it's additional work to update a Curse page every time we make a new build.  There's also the complication that Galacticraft add-ons can need specific Galacticraft versions so they won't want auto-updating to the latest.  I guess it's possible in future we will move to a mixed system where our promoted builds get added to Curse.

**Comment by Thyriel** [comment]
>There's also the complication that Galacticraft add-ons can need specific Galacticraft versions so they won't want auto-updating to the latest.
It's more a semi-automatic update process as you still need to manually hit the update button for every mod in the twitch client. Imho if an addon mod relays on a specific GC version they should just use the forge method of specifying a min/max version number so forge refuses to launch the game when GC version is too high.

**Comment by radfast** [comment]
Sure.  But the addons don't always do that (for example they wouldn't usually specify a **max** GC version because they don't yet know which future version of GC they will not be compatible with).  We have recently introduced changes to make this more accessible for addons so I think it's getting better.

**Comment by Ku1t-PiIPE** [comment]
this is a big problem for me as well

**Comment by MJRLegends** [comment]
Its really not a issue, you still get approval on your mod packs..

**Comment by Ku1t-PiIPE** [comment]
how?

**Comment by EzerArch** [comment]
https://github.com/micdoodle8/Galacticraft#modpacks

**Comment by sfxworks** [comment]
:) https://minecraft.curseforge.com/projects/lapitos-galacticraft

**Comment by Flipp3rrr** [comment]
For modpack creators that want GalactiCraft in their Twitch pack:
1. Export your modpack
2. Unzip your modpack
3. Add GalactiCraft to the mod folder inside the unzipped pack
4. Zip it again and upload to CurseForge

**Comment by MJRLegends** [comment]
Or just add it in the mods folder before exporting it and it will carry it across for you

**Comment by BraveCaperCat2** [comment]
Please upload the mod on curseforge.
It is a pain for modpack developers (such as me) to have to install mods not on curseforge - and i can't add "curseforge approved mods not on curseforge" into the modpack like REGULAR MODS.

**Comment by MJRLegends** [comment]
Its already on there

**Comment by ROMVoid95** [comment]
@BraveCaperCat2 it's been on curseforge for over a year and half.

**Comment by EzerArch** [comment]
> Please upload the mod on curseforge.

@BraveCaperCat2, like this? https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy It's been there since Jan 4, 2022.

BTW, our new repo is https://github.com/TeamGalacticraft/Galacticraft.

**Comment by BraveCaperCat2** [comment]
> > Please upload the mod on curseforge.
> 
> @BraveCaperCat2, like this? https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy It's been there since Jan 4, 2022.
> 
> BTW, our new repo is https://github.com/TeamGalacticraft/Galacticraft.

Um - Isn't galaticraft legacy an outdated version - also would like to note your website downloads are broken - you should try them.
Also this was linked to by the galacticraft page (i think) - the wiki.

**Comment by ROMVoid95** [comment]
> > > Please upload the mod on curseforge.
> > 
> > 
> > @BraveCaperCat2, like this? [curseforge.com/minecraft/mc-mods/galacticraft-legacy](https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy) It's been there since Jan 4, 2022.
> > BTW, our new repo is [TeamGalacticraft/Galacticraft](https://github.com/TeamGalacticraft/Galacticraft).
> 
> Um - Isn't galaticraft legacy an outdated version - also would like to note your website downloads are broken - you should try them. Also this was linked to by the galacticraft page (i think) - the wiki.

Incorrect, Legacy is a reworked 1.12.2 version to be only 1 jar (versus 3) and contains any updates to the 1.12.2 version past build .280 (currently 4.0.5 is the latest)

We are aware the rebranded website is not working, we do not have any control over the site as it was sold to a third party, any versions that were on the downloads can be found here [GalacticArchive](https://files.galacticraft.net/GalacticArchive/)

**Comment by BraveCaperCat2** [comment]
> > > > Please upload the mod on curseforge.
> > > 
> > > 
> > > @BraveCaperCat2, like this? [curseforge.com/minecraft/mc-mods/galacticraft-legacy](https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy) It's been there since Jan 4, 2022.
> > > BTW, our new repo is [TeamGalacticraft/Galacticraft](https://github.com/TeamGalacticraft/Galacticraft).
> > 
> > 
> > Um - Isn't galaticraft legacy an outdated version - also would like to note your website downloads are broken - you should try them. Also this was linked to by the galacticraft page (i think) - the wiki.
> 
> Incorrect, Legacy is a reworked 1.12.2 version to be only 1 jar (versus 3) and contains any updates to the 1.12.2 version past build .280 (currently 4.0.5 is the latest)
> 
> We are aware the rebranded website is not working, we do not have any control over the site as it was sold to a third party, any versions that were on the downloads can be found here [GalacticArchive](https://files.galacticraft.net/GalacticArchive/)

ah.
