### ISSUE TITLE
Spin Thrusters floating away issue & Head stuck on the roof

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2170]
## **Information on issue:**

Right I have 4 thrusters on my space station, when I float in the area without a jetpack I begin to move round with the spinning of the station. This isn't gravity? it can get annoying when I move and I float up then get floated to the other side of the station.

Also if I float to far upwards I become stuck to the roof and have to break the block to get down which is very annoying.

To be honest its easier to move around without the Spin Thrusters which shouldn't be the case as they are designed to help it.....

I know this has probably been reported already but please help me out with this issue as its seems to be a issue with everyone not just me..
## Examples:

**Floating with the spinning:**
![](https://i.gyazo.com/ee300f3f899fdcbb80b5ca20cbf77589.gif)

**Stuck to the roof:**
![](https://i.gyazo.com/709237f8f9c7847652df105ffad14aa3.gif)

**Comment by dj3520** [comment]
>Floating with the spinning

Pretty sure this is caused by being too far away from the spin thrusters. You become "disconnected" from the station and move separately from it.

>Stuck to the roof

Could I verify that this only happens in instances where the spinning view is present? If so then I can confirm that I'm having the same issue. I was going to make an issue but my video recording was a bit too dark.

**Comment by Creeperman8362** [comment]
I think your oxygen seal has a hole in it.

**Comment by EzerArch** [comment]
>I think your oxygen seal has a hole in it.

@Creeperman8362, care to explain what "having a hole in it(?)" has to do with spin thrusters and getting stuck in the ceiling?

**Comment by Creeperman8362** [comment]
like your station has a hole in it and your oxygen cannot seal it. i made a station with spinners, and if i punched a hole in the wall, breaking the o2 seal, i would spin with the station and cant move around up or down. im just trying to help.

**Comment by EzerArch** [comment]
> Im just trying to help.

@Creeperman8362, thanks for trying to help, it's much appreciated, but don't get me wrong, before posting on any Github issue:
1. Learn carefully what the issue is about.
2. Make sure your post is based on evidence or technical background, or at least contains helpful debugging information. 
3. Avoid posting guesses, speculations or vague comments: these will not help. Please elaborate. From what I have seen in your recent activity, you tend to post unwary comments (example [1](https://github.com/micdoodle8/Galacticraft/issues/2158#issuecomment-199535868) an [2](https://github.com/micdoodle8/Galacticraft/issues/2158#issuecomment-200200614)). :wink:

**Comment by MJRLegends** [comment]
Any news on this issue?

**Comment by EzerArch** [comment]
@MJRLegends:
> This isn't gravity?

No. It's centrifugal force, that is, a force that pushes you outwards and can be measured in G-Force but it is not gravity like in the overworld:

> When a space station is spinning it will create a G-Force which varies depending on how large the station is and how fast it is spinning. This G-Force creates an effect that will push you outward from the center of gravity of the station based on centrifugal force. The amount of force increases the further you are from the space station's center of gravity. This effect only applies while you are floating near a contact surface such as a long wall. It does not affect the player if your feet are planted on the floor, in which case you may walk around normally.
(From: https://wiki.micdoodle8.com/wiki/Overworld_Space_Station#Effects)

2:
> Also if I float to far upwards I become stuck to the roof and have to break the block to get down which is very annoying.

This is indeed a problem, but I think it was fixed: https://github.com/micdoodle8/Galacticraft/issues/1833

**Comment by dj3520** [comment]
#1833 fixed this issue when spin thrusters are not used.

**Comment by MJRLegends** [comment]
Any news on this issue being fixed full?

**Comment by dj3520** [comment]
Still having this issue with 463 on my friend's server.

As far as what causes the stuck to the roof issue, I've noticed that if this happens and you move until the ceiling moves up, just as you leave you'll move upwards. I'd imagine the reason you can't go down is because the freefall logic is still moving you upwards, and for some reason not seeing that you aren't. in fact holding space while stuck and then sliding out can end up launching you.

**Comment by dj3520** [comment]
Seems the "launching" aspect is gone or I've forgot how I did it, but example video of what I'm seeing is at https://youtu.be/qQZI4_M_FKw

**Comment by EzerArch** [comment]
> I'm seeing is at https://youtu.be/qQZI4_M_FKw

0:50 that's a vanilla bug (https://bugs.mojang.com/browse/MC-8898). Not that hitbox is glitchy, but the the debug tool renders the hitbox's outline wrong.

"Launching" problem and others are very old: https://github.com/micdoodle8/Galacticraft/issues/1383#issuecomment-70144010

**Comment by dj3520** [comment]
@EzerArch 
>that's a vanilla bug

Well that's annoying. Don't think they'll put out a mod update for 1.7.10 to fix that :laughing:

>"Launching" problem and other bugs are very old: 

Those seem to be blaming a MPS interaction, but I feel like I managed to do it without. Can't do it now so not something I can really test for.

>I honestly couldn't reproduce it.

I just tested with 0 other mods (besides client-side.) Seeing the structure "maker" strangeness now. Doesn't seem to happen in the starting space station that is generated, but anything more than 4 blocks high otherwise gets me stuck. Strange since my other video proves 3 high, but that was with a ton of mods. Video https://youtu.be/uf8trToBimg

Tested if the arrival structure was immune on my friend's server and it is, but strangely now on my platform I made I can only reproduce the issue with 4 block high spaces and not with 3.

**Comment by radfast** [comment]
> Right I have 4 thrusters on my space station, when I float in the area without a jetpack I begin to move round with the spinning of the station. This isn't gravity? it can get annoying when I move and I float up then get floated to the other side of the station.

This is intended behaviour, and is correct.  The station is spinning, you are not, so it will look like you are moving relative to different parts of the station.  If you don't follow this, [further reading](https://en.wikipedia.org/wiki/Newton%27s_laws_of_motion#Newton.27s_first_law).  Or watch the movie _Gravity_ (which actually is all about a zero gravity environment) ... :)

> Also if I float too far upwards I become stuck to the roof and have to break the block to get down which is very annoying.

Looking at @dj3520 video (thank you for that, good job!) it looks like it's an issue only with spaces 4 blocks high **or higher** and no walls nearby.   I am able to reproduce the issue in my test environment, now looking to fix this...

**Comment by MJRLegends** [comment]
@radfast yeah the second point is the main issue  (one about sticking to the roof)

**Comment by radfast** [comment]
That head sticking issue is fixed from build 482.

**Comment by MJRLegends** [comment]
yayy @radfast thanks
