### ISSUE TITLE
[1.10.2-Build-76] Rocket fuel

### ISSUE THREAD

**Issue by bortooo** [micdoodle8/Galacticraft#2646]
Fuel loader doesn't accept Rocket Fuel from Ender IO mod.
![2017-04-27_21 00 48](https://cloud.githubusercontent.com/assets/28114042/25499733/b4c849e8-2b8c-11e7-9eb2-1f63bc6b1fc9.png)

**Comment by kenijey** [comment]
such a nice compatibility issue

**Comment by radfast** [comment]
hmm it should do, it does in other GC versions.

**Comment by radfast** [comment]
this is fixed already in next build 77, I think - it was actually the Forge bucket which Galacticraft wasn't recognising, not the Rocket Fuel!

**Comment by bortooo** [comment]
Thanks! It's nice to help you.

**Comment by radfast** [comment]
[Build 77 now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/)

**Comment by bortooo** [comment]
I have tested Build-77 and now fuel loader can accept rocket fuel but it still doesn't accpet forge bucket.

**Comment by radfast** [comment]
thanks for the further testing.

I've made some more additions to next build 78, so that it should be compatible in 1.10.2 with Forge buckets and other mod items like Pressure Pipes.  (This compatibility is already present in 1.11.2.  In 1.10.2 we are aiming for dual compatibility with both of the approaches which other mods can take to containers)

**Comment by bortooo** [comment]
Thanks again!
I hope release will be out as soon as possible.

**Comment by kenijey** [comment]
bdw @radfast , please add moons to other planets :) for example titan of saturn :D saturn has many moons tho

**Comment by bortooo** [comment]
@kenijey In 1.7 there were a lot of addons to GC that add a lot of planets and moons. In 1.10 there is only [ExtraPlanets](https://minecraft.curseforge.com/projects/extraplanets)

**Comment by kenijey** [comment]
i'm playing on 1.11.2, no addons for GC4 :D

**Comment by radfast** [comment]
> please add moons to other planets :) for example titan of saturn :D 

Not gonna happen any time soon in Galacticraft itself.  We don't want bland destinations, we want planets and moons with a custom look, different skybox, new ores and rocks, new mobs, new damage sources, and unique rare or treasure items....   The outer planets and moons will also need to have different mechanics because gaseous elements like oxygen and nitrogen are probably liquids there...

I expect many or most of the add-ons will be updating to 1.10+, so just be patient and enjoy what's already in the game.

**Comment by kenijey** [comment]
hmmm... i understood. thanks for the reply :)
