### ISSUE TITLE
Galacticraft crashed the server the first time generating Venus and each subsequent login

### ISSUE THREAD

**Issue by BlitzAce71** [micdoodle8/Galacticraft#3004]
Minecraft version: 1.11.2
Galacticraft version: 1.11.2-4.0.0.117
Forge version: 1.11.2-13.20.0.2315

Single player (SSP) or Multiplayer (SMP)? SMP

Galacticraft add-ons and other mods installed?
minecraft{1.11.2} [Minecraft] (minecraft.jar) 
mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2315-universal.jar) 
forge{13.20.0.2315} [Minecraft Forge] (forge-1.11.2-13.20.0.2315-universal.jar) 
Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
animania{1.0.4.7} [Animania] (animania-1.11.2-1.0.4.7.jar) 
biomesoplenty{6.2.0.2254} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.2.0.2254-universal.jar) 
craftstudioapi{0.3.0-beta} [CraftStudio API] (CraftStudioAPI-universal-0.3.0.86-mc1.11.2-beta.jar) 
dimensionrules{1.1} [Dimension Rules] (DimensionRules-MC1.11-1.1.jar) 
galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.11.2-4.0.0.117.jar) 
galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.11.2-4.0.0.117.jar) 
extraplanets{0.3.8} [Extra Planets] (ExtraPlanets-0.3.8.jar) 
zerocore{1.11.2-0.1.0.6} [Zero CORE] (zerocore-1.11.2-0.1.0.6.jar) 
bigreactors{1.11.2-0.4.5.30} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.30.jar) 
inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
ironchest{1.11.2-7.0.25.815} [Iron Chest] (ironchest-1.11.2-7.0.25.815.jar) 
jei{4.5.0.294} [Just Enough Items] (jei_1.11.2-4.5.0.294.jar) 
journeymap{1.11.2-5.5.0} [JourneyMap] (journeymap-1.11.2-5.5.0.jar) 

Please provide screenshots / crash report / log as needed.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  LoadingPlugin (DimensionRules-MC1.11-1.1.jar)
  MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.117.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/11/17 12:00 AM
Description: Exception preparing structure feature

java.lang.NullPointerException: Exception preparing structure feature
	at micdoodle8.mods.galacticraft.planets.venus.world.gen.dungeon.RoomBossVenus.getNextPiece(RoomBossVenus.java:237)
	at micdoodle8.mods.galacticraft.planets.venus.world.gen.dungeon.DungeonStartVenus.func_74861_a(DungeonStartVenus.java:45)
	at micdoodle8.mods.galacticraft.planets.venus.world.gen.dungeon.MapGenDungeonVenus$Start.<init>(MapGenDungeonVenus.java:94)
	at micdoodle8.mods.galacticraft.planets.venus.world.gen.dungeon.MapGenDungeonVenus.func_75049_b(MapGenDungeonVenus.java:72)
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:40)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:34)
	at micdoodle8.mods.galacticraft.planets.venus.world.gen.ChunkProviderVenus.func_185932_a(ChunkProviderVenus.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:144)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at micdoodle8.mods.galacticraft.planets.venus.world.gen.dungeon.RoomBossVenus.getNextPiece(RoomBossVenus.java:237)
	at micdoodle8.mods.galacticraft.planets.venus.world.gen.dungeon.DungeonStartVenus.func_74861_a(DungeonStartVenus.java:45)
	at micdoodle8.mods.galacticraft.planets.venus.world.gen.dungeon.MapGenDungeonVenus$Start.<init>(MapGenDungeonVenus.java:94)
	at micdoodle8.mods.galacticraft.planets.venus.world.gen.dungeon.MapGenDungeonVenus.func_75049_b(MapGenDungeonVenus.java:72)

-- Feature being prepared --
Details:
	Is feature chunk: True
	Chunk location: -15,-44
	Chunk pos hash: -184683593743
	Structure type: micdoodle8.mods.galacticraft.planets.venus.world.gen.dungeon.MapGenDungeonVenus
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:40)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:34)
	at micdoodle8.mods.galacticraft.planets.venus.world.gen.ChunkProviderVenus.func_185932_a(ChunkProviderVenus.java:190)

-- Chunk to be generated --
Details:
	Location: -23,-46
	Position hash: -193273528343
	Generator: micdoodle8.mods.galacticraft.planets.venus.world.gen.ChunkProviderVenus@2caae022
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:144)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)

-- Affected level --
Details:
	Level name: aaaaaaaaagh
	All players: 1 total; [GCEntityPlayerMP['BlitzAce71'/956143, l='aaaaaaaaagh', x=-382.50, y=900.00, z=-733.50]]
	Chunk stats: ServerChunkCache: 7 Drop: 0
	Level seed: -9134626163274414725
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 4.9.33-mod-std-ipv6-64
	Java Version: 1.8.0_112, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 537610080 bytes (512 MB) / 2293235712 bytes (2187 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms256M -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 11, tallocated: 256
	FML: MCP 9.38 Powered by Forge 13.20.0.2315 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2315-universal.jar) 
	UCHIJAAAA	forge{13.20.0.2315} [Minecraft Forge] (forge-1.11.2-13.20.0.2315-universal.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	animania{1.0.4.7} [Animania] (animania-1.11.2-1.0.4.7.jar) 
	UCHIJAAAA	biomesoplenty{6.2.0.2254} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.2.0.2254-universal.jar) 
	UCHIJAAAA	craftstudioapi{0.3.0-beta} [CraftStudio API] (CraftStudioAPI-universal-0.3.0.86-mc1.11.2-beta.jar) 
	UCHIJAAAA	dimensionrules{1.1} [Dimension Rules] (DimensionRules-MC1.11-1.1.jar) 
	UCHIJAAAA	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.11.2-4.0.0.117.jar) 
	UCHIJAAAA	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.11.2-4.0.0.117.jar) 
	UCHIJAAAA	extraplanets{0.3.8} [Extra Planets] (ExtraPlanets-0.3.8.jar) 
	UCHIJAAAA	zerocore{1.11.2-0.1.0.6} [Zero CORE] (zerocore-1.11.2-0.1.0.6.jar) 
	UCHIJAAAA	bigreactors{1.11.2-0.4.5.30} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.30.jar) 
	UCHIJAAAA	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.25.815} [Iron Chest] (ironchest-1.11.2-7.0.25.815.jar) 
	UCHIJAAAA	jei{4.5.0.294} [Just Enough Items] (jei_1.11.2-4.5.0.294.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.5.0} [JourneyMap] (journeymap-1.11.2-5.5.0.jar) 
	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (DimensionRules-MC1.11-1.1.jar)
  lumien.dimensionrules.asm.ClassTransformer
MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.117.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Profiler Position: N/A (disabled)
	Player Count: 3 / 100; [GCEntityPlayerMP['DocHM1'/889324, l='aaaaaaaaagh', x=285.44, y=68.00, z=-899.46], GCEntityPlayerMP['phonk99'/930092, l='aaaaaaaaagh', x=465.92, y=67.00, z=-1662.65], GCEntityPlayerMP['BlitzAce71'/956143, l='aaaaaaaaagh', x=-382.50, y=900.00, z=-733.50]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by BlitzAce71** [comment]
I should clarify, each subsequent login by the player that generated Venus (me) crashes the server, but if I'm not logged in everything else continues to work.

**Comment by radfast** [comment]
Haven't seen this before.  It looks like this is just very bad luck with the Random Number Generator, something connected with your world seed.

We'll work on a fix for you, might be a day or two.  When it's ready I'll notify in this thread.

**Comment by BlitzAce71** [comment]
Thank you so much radfast! I also wonder if this has something to do with a different crash we've been getting, which has to do with accessing some of the machinery (arc furnaces, electric compressors, etc.) placed by one specific player on our server. Every other player's machines work fine, but if this particular player places machines on the overworld, anyone who accesses them crashes the server. If he places them in another dimension, everything works fine. I can post that crash report as a second topic here, but I wonder if it would shed any light on this venus crash or if the two are more likely unrelated?

Thank you for all of the hard work, this is the best Minecraft mod I've ever played!

**Comment by radfast** [comment]
Thanks for your words, sorry the response is slower than I hoped (real life issues...)

Please post that other crash report as a second topic.  It's likely unrelated.  You should also note that was an update specifically for Arc Furnaces going from build 117 -> build 118 so you might find the problem is now fixed, I'll be able to tell immediately when I see that crash report.

**Comment by BlitzAce71** [comment]
Ok thank you! Our galacticraft server is currently offline but I will try to reproduce that crash report when it comes back up. We have several players ready to move on to Venus, so that bug currently takes priority with our server. Thank you!

**Comment by BlitzAce71** [comment]
Posted the above crash in another topic. Venus still not working for anyone. Thank you!

**Comment by radfast** [comment]
Build 119 will be available later today, and should have fixed this issue so that your Venus now works.  (You might want to delete the whole dimension DIM-31 and let the server re-create it, if nobody built anything there yet...)

Any more problems, please comment or re-open.  We want to have it working for you!
