### ISSUE TITLE
Galacticraft 4: Pipes & Wires stops working periodically, reason unknown

### ISSUE THREAD

**Issue by kouwei32** [micdoodle8/Galacticraft#3020]
I was building my space station when my equipments started to fail. Most machinery don't output (but accepts) resources periodically. No errors in log. Sometimes fixed by block update. Could be caused by my abundant use of the block that has pipe/wire in it.

Screenshots (**Look at the pipe on the right, it's not outputting**):

![gcbug1](https://user-images.githubusercontent.com/29967594/32127742-d4d31098-bb2d-11e7-8dcd-3d708a7cf3ac.jpg)

![gcbug2](https://user-images.githubusercontent.com/29967594/32127748-deb48a60-bb2d-11e7-9b62-b55bf8d14a91.jpg)

Minecraft version: 1.11.2
Galacticraft version: 4.0.0.106
Forge version: 13.20.1.2386

Single player (SSP) or Multiplayer (SMP)?
SSP.

Galacticraft add-ons and other mods installed?
No add-on mods, extra mods include Optifine, MrCF Furniture, and Buildcraft.

**Comment by kouwei32** [comment]
This is not a duplicate of Issue #2567, because this works periodically, not always faulty.

**Comment by TheQuadShot** [comment]
I would recommend you update to the version 1.11.2-4.0.0.118 

https://micdoodle8.com/mods/galacticraft/downloads

**Comment by radfast** [comment]
^^^^^^^^^^^^^^^^^^^

**Comment by radfast** [comment]
This might be better again, in next build 119.  Build 119 has improved the mod's response to block updates.

@kouwei32  if you're still having issues in build 119, please can you let me know.

**Comment by spylor** [comment]
I still have this issue in 119. Not sure how periodically it is though. I see it when my canister I leave in the Compressor isn't full. I have to hit the pipes with the wrench for the oxygen to flow again, or rebuild the pipes. It happens if the pipes are in neutral, but also if the side of the oxygen collector is in output only mode.

**Comment by radfast** [comment]
Possible the same issue as #2966, if this is happening client side only (so server side things are still actually working, only you can't see them right).

**Comment by spylor** [comment]
Possibly, but the machines stop working also.
________________________________

**Comment by radfast** [comment]
@spylor thanks for your patience

any chance you can test whether this is still an issue for you in the latest Galacticraft?   If so, please give me a screenshot so I can build the same and test it.

**Comment by spylor** [comment]
Give me some time.
________________________________

**Comment by TheQuadShot** [comment]
I wonder if this is a problem of part of your base being chunk loaded and part of it not being loaded. You may want to try using ChickenChunks/FTBUtils and testing again. Also iirc the biggest problem with sealing a structure are the number of Oxygen Sealers, not the amount of oxygen being supplied.

**Comment by kouwei32** [comment]
After adding a chunk loader, my pipes and oxygen sealers seems to be working fine, but sometimes the pipes have visual issues where they look different from their actual state.

P.S. The Oxygen Storage Modules in 1.12.2 always have a full bar on the outside. Probably should be fixed.

**Comment by d1kong2** [comment]
I seem to be having this issue on my server now with the newest version installed(1.12)
i use the fluid pipes for all my fluid needs, lava, oil, liquid meat. Sometimes when i come back to an area all the pipes that where set to drain where on neutral, i thought it was just visual but the machines depending on said fluids stopped getting said fluid. 
Just thought id post that its still happening.
