### ISSUE TITLE
Texture and Performance Issues

### ISSUE THREAD

**Issue by Yspatil** [micdoodle8/Galacticraft#3469]
Moon rock has the texture of the copper ore found on the moon.

Also the grating block causes short lag spikes when I go to place or break other blocks in the vicinity of the grating block.

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP opened to LAN

Galacticraft add-ons and other mods installed?

![capture](https://user-images.githubusercontent.com/26679487/42415296-8e3d89a4-8217-11e8-9b2f-c15378ead51b.PNG)

Please provide screenshots / crash report / log as needed.
![2018-07-07_18 41 48](https://user-images.githubusercontent.com/26679487/42415305-cc18f150-8217-11e8-9d0f-343c9be3f54d.png)

**Comment by gonenoculer5** [comment]
Can confirm this issue also happened on my pack, and was about to report it, cheers.

**Comment by MasterEnderman** [comment]
This can easily be fixed by changeing the basic_block_moon.json from
```
{
    "forge_marker": 1,
    "variants": {
        "inventory": [{ "model": "galacticraftcore:ore_copper_moon_model" }],
        "basictypemoon=ore_copper_moon": { "model": "galacticraftcore:ore_copper_moon_model" },
        "basictypemoon=ore_tin_moon": { "model": "galacticraftcore:ore_tin_moon_model" },
        "basictypemoon=ore_cheese_moon": { "model": "galacticraftcore:ore_cheese_moon_model" },
        "basictypemoon=moon_dirt_moon": { "model": "galacticraftcore:moon_dirt_moon_model" },
        "basictypemoon=moon_stone": { "model": "galacticraftcore:moon_stone_model" },
        "basictypemoon=moon_turf": { "model": "galacticraftcore:moon_turf_model" },
        "basictypemoon=ore_sapphire_moon": { "model": "galacticraftcore:ore_sapphire_moon_model" },
        "basictypemoon=moon_dungeon_brick": { "model": "galacticraftcore:moon_dungeon_brick_model" }
    }
}
```
to
```
{
    "forge_marker": 1,
    "variants": {
        "inventory": [
            {
                "model": "galacticraftcore:moon_stone_model"
            }
        ],
        "basictypemoon=ore_copper_moon": {
            "model": "galacticraftcore:ore_copper_moon_model"
        },
        "basictypemoon=ore_tin_moon": {
            "model": "galacticraftcore:ore_tin_moon_model"
        },
        "basictypemoon=ore_cheese_moon": {
            "model": "galacticraftcore:ore_cheese_moon_model"
        },
        "basictypemoon=moon_dirt_moon": {
            "model": "galacticraftcore:moon_dirt_moon_model"
        },
        "basictypemoon=moon_stone": {
            "model": "galacticraftcore:moon_stone_model"
        },
        "basictypemoon=moon_turf": {
            "model": "galacticraftcore:moon_turf_model"
        },
        "basictypemoon=ore_sapphire_moon": {
            "model": "galacticraftcore:ore_sapphire_moon_model"
        },
        "basictypemoon=moon_dungeon_brick": {
            "model": "galacticraftcore:moon_dungeon_brick_model"
        }
    }
}
```
Related File: https://github.com/micdoodle8/Galacticraft/blob/c5d86fda38c8e5f4efa9a07b8ea86e6630b51d46/src/main/resources/assets/galacticraftcore/blockstates/basic_block_moon.json

**Comment by radfast** [comment]
@MasterEnderman  I don't understand why your change fixes this - apart from formatting changes, the only thing you have changed is the `#inventory` variant.  The `#inventory` variant should not be being rendered in the game unless something has gone badly wrong.

**Comment by MasterEnderman** [comment]
I don't really know either, i just experimented around and overwrited the original basic_block_moon.json using a mod called resourceloader and loaded in the one with the chnged `#inventory` varian. that fixed it for me.
But honestly i have no idea which other mod in my pack (170 in total) could cause something like that. As it is the only block in the complete pack with this behavior.

**Comment by Yspatil** [comment]
Okay I did the 3 tests and the texture is still broken. I tried updating minecraft forge, reinstalling galacticraft and all the mods associated with it, and even reinstalled minecraft as a whole but I still had no success. Also, just to clarify, the texture problem only happens when the moon rock is in my inventory or in a container block (e.g. chest) but the texture looks fine when the block is placed.

As for the lag problem with the grating block, that seemed to fix itself after I updated forge and reinstalled galacticraft.

![2018-07-30_10 49 47](https://user-images.githubusercontent.com/26679487/43408442-637624f8-93ef-11e8-9efc-8090c847f029.png)

**Comment by MasterEnderman** [comment]
@Yspatil Out of curiosity could you try my method as well with adding the "resourceloader" mod to your pack and overwriting the `basic_block_moon.json` and see if it fixes it for you? if you need further advise on how to accomplish that feel free to ask.

**Comment by TJHeim** [comment]
I have been testing this in solely Galacticraft and I'm quite sure that in at least v1.12.2-4.0.1.178 up to 181 have this bug. 

I can confirm that the glitch is in the basic_block_moon.json file:
` "forge_marker": 1,
    "variants": {
        "inventory": [{ "model": "galacticraftcore:ore_copper_moon_model" }],
        "basictypemoon=ore_copper_moon": { "model": "galacticraftcore:ore_copper_moon_model" },
        "basictypemoon=ore_tin_moon": { "model": "galacticraftcore:ore_tin_moon_model" },
        "basictypemoon=ore_cheese_moon": { "model": "galacticraftcore:ore_cheese_moon_model" },
        "basictypemoon=moon_dirt_moon": { "model": "galacticraftcore:moon_dirt_moon_model" },
        "basictypemoon=moon_stone": { "model": "galacticraftcore:moon_stone_model" },
        "basictypemoon=moon_turf": { "model": "galacticraftcore:moon_turf_model" },
        "basictypemoon=ore_sapphire_moon": { "model": "galacticraftcore:ore_sapphire_moon_model" },
        "basictypemoon=moon_dungeon_brick": { "model": "galacticraftcore:moon_dungeon_brick_model" }
    }`

As far as I understand the error is the model that the inventory uses on line 3 of this block. It should be changed to:
` "forge_marker": 1,
    "variants": {
        "inventory": [{ "model": "galacticraftcore:basic_block_moon" }],
        "basictypemoon=ore_copper_moon": { "model": "galacticraftcore:ore_copper_moon_model" },
        "basictypemoon=ore_tin_moon": { "model": "galacticraftcore:ore_tin_moon_model" },
        "basictypemoon=ore_cheese_moon": { "model": "galacticraftcore:ore_cheese_moon_model" },
        "basictypemoon=moon_dirt_moon": { "model": "galacticraftcore:moon_dirt_moon_model" },
        "basictypemoon=moon_stone": { "model": "galacticraftcore:moon_stone_model" },
        "basictypemoon=moon_turf": { "model": "galacticraftcore:moon_turf_model" },
        "basictypemoon=ore_sapphire_moon": { "model": "galacticraftcore:ore_sapphire_moon_model" },
        "basictypemoon=moon_dungeon_brick": { "model": "galacticraftcore:moon_dungeon_brick_model" }
    }`

This is because putting the copper_moon_model as the base inventory model for basic_moon_block seems to make basic_moon_block 4's inventory skin set to copper ore. There might be more to this  though as I am not sure why it only affects this block and not any others in the file.

**Comment by TJHeim** [comment]
In furthering of this issue, looking at the ground blocks for Mars and Venus I found that they don't contain the #inventory model. but the Asteroids blocks do. Could someone please explain what this variant is used for?

**Comment by radfast** [comment]
The #inventory variant is not used by Galacticraft - at least, it should not be being used.  It is included only because Forge logs an error in startup if there is no #inventory variant.

The solution of changing the resource .json file is not a good solution, it will simply cause the same issue to be seen with some other Moon block.  That's because that .json is shared by a number of different Moon Blocks.  We had to pick one of them for the (unused) #inventory variant, and the one we happened to pick was Copper Ore.

The real issue here is why is the `#inventory` variant being drawn at all.  It seems likely that it's some change between Forge versions, because this did not used to happen.

**Comment by micdoodle8** [comment]
I wasn't able to reproduce this, with or without JEI. It's possible the source of the problem has been fixed in GC, JEI, or Forge.

I've changed the `#inventory` variant as mentioned above. I do agree with radfast, but I'm also not sure why the copper model was used in the basic_block_moon.json as the inventory model in the first place. Probably an error on my end.

Now the question is does the copper ore model appear as moon rock?
